services:
  app:
    container_name: my_project_app
    build: ./
    depends_on:
      - rabbitmq
      - db
    command: >
      uvicorn app.apps.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/src
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env.docker
    environment:
      - PYTHONPATH=/src
  rabbitmq:
    container_name: my_project_message_broker
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RMUSER}
      - RABBITMQ_DEFAULT_PASS=${RMPASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  db:
    container_name: my_project_db
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
    restart: always
  redis:
    container_name: my_project_redis
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
  worker:
    build: .
    working_dir: /src
    command: celery -A app.apps.core.celery_config:celery_app worker -l INFO
    volumes:
      - .:/src
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PYTHONPATH=/src
    env_file:
      - .env.docker
volumes:
  redis-data:
  db-data:

